### ISSUE TITLE
I copy a Objective-C version and add 24 hour calculate method.

### ISSUE THREAD

**Issue by Nikolilol** [LeonardoCardoso/BedtimeClock#8]
Hi Cardoso,
I`m very grateful for this library.
And I translate this library from SWIFT to Objective-C.
Also I just add 24 hours calculate method that for your reference.

Link for OC version: https://github.com/Nikolilol/NKBedtimeClock-master
Thank you.

**Comment by LeonardoCardoso** [comment]
Thanks, @Nikolilol. I will copy your 24 hr approach when I have time. 😄
